### ISSUE TITLE
Segfault gltfpack linux 64bit fedora 30

### ISSUE THREAD

**Issue by arpu** [zeux/meshoptimizer#39]
master cc463d75979ff2508568d3a9171c89ca50ebdb66
```
./gltfpack -v -i /home/arpu/Work/projects/vrland_assetssrc/models/bentley/bentley.glb -o bent.glb                                                                                                                                    ✔  10158  15:57:25 
input: 174 nodes, 170 meshes, 0 skins, 0 animations
meshes: 1332023 triangles, 1086730 vertices
[1]    3449 segmentation fault (core dumped)  ./gltfpack -v -i  -o bent.glb

```

i think i need debug builds and do some gdb

**Comment by arpu** [comment]
```
Reading symbols from ./gltfpack...
(gdb) run -v -i /home/arpu/Work/projects/vrland_assetssrc/models/bentley/bentley.glb -o bent.glb
Starting program: /home/arpu/Work/githubsources/meshoptimizer/gltfpack -v -i /home/arpu/Work/projects/vrland_assetssrc/models/bentley/bentley.glb -o bent.glb
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-12.fc30.x86_64
input: 174 nodes, 170 meshes, 0 skins, 0 animations
meshes: 1332023 triangles, 1086730 vertices

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bd1f95 in __strlen_avx2 () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install libgcc-9.1.1-1.fc30.x86_64 libstdc++-9.1.1-1.fc30.x86_64
(gdb) bt full
#0  0x00007ffff7bd1f95 in __strlen_avx2 () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff7ee5689 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+=(char const*) () from /lib64/libstdc++.so.6
No symbol table info available.
#2  0x000000000041a682 in process (scene=..., settings=..., json="", bin="") at tools/gltfpack.cpp:1439
        image = @0x46d100: {name = 0x46d1d0 "Image_3", uri = 0x0, buffer_view = 0x46d908, mime_type = 0x46d1b0 "image/png"}
        i = 0
        data = 0x4530a0
        qp = {pos_offset = {-1.14263856, -0.000703662634, -2.63861775}, pos_scale = 4.83839035, pos_bits = 14, uv_offset = {-2399.79492, -1098.69849}, uv_scale = {2475.4895, 1275.89636}, uv_bits = 12}
        json_images = "{\"uri\":\""
        json_textures = ""
        json_materials = ""
        json_buffer_views = ""
        json_accessors = ""
        json_meshes = ""
        json_nodes = ""
        json_skins = ""
        json_roots = ""
        json_animations = ""
        has_pbr_specular_glossiness = false
        view_offset = 0
        node_offset = 0
        mesh_offset = 0
        bytes_vertex = 0
        bytes_index = 0
        bytes_skin = 0
        bytes_time = 0
        bytes_keyframe = 0
        node_keep = std::vector<bool> of length -1125882108920646, capacity -1125898829637248 = {1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 
          0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0...}
        node_named = std::vector<bool> of length 34299809308, capacity 1125898727242048 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
          0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
          0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}
        node_remap = std::vector of length 35182226037202, capacity -2112495450 = {<error reading variable node_remap (Cannot access memory at address 0x1f7a87d68)>
#3  0x000000000041e643 in main (argc=6, argv=0x7fffffffdbe8) at tools/gltfpack.cpp:2143
        settings = {pos_bits = 14, uv_bits = 12, anim_freq = 30, compress = false, verbose = true}
        input = 0x7fffffffdfc0 "/home/arpu/Work/projects/vrland_assetssrc/models/bentley/bentley.glb"
        output = 0x7fffffffe008 "bent.glb"
```
cpu flags available:
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

**Comment by arpu** [comment]
here with more debug infos 
```
 run -v -i /home/arpu/Work/projects/vrland_assetssrc/models/bentley/bentley.glb -o bent.glb
Starting program: /home/arpu/Work/githubsources/meshoptimizer/gltfpack -v -i /home/arpu/Work/projects/vrland_assetssrc/models/bentley/bentley.glb -o bent.glb
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-12.fc30.x86_64
warning: Loadable section ".note.gnu.property" outside of ELF segments
warning: Loadable section ".note.gnu.property" outside of ELF segments
input: 174 nodes, 170 meshes, 0 skins, 0 animations
meshes: 1332023 triangles, 1086730 vertices

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bd1f95 in __strlen_avx2 () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff7bd1f95 in __strlen_avx2 () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007ffff7ee5689 in std::char_traits<char>::length (__s=0x0) at /usr/src/debug/gcc-9.1.1-1.fc30.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/char_traits.h:335
No locals.
#2  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append (__s=0x0, this=0x7fffffffd1f0) at /usr/src/debug/gcc-9.1.1-1.fc30.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1266
        __n = <optimized out>
        __n = <optimized out>
#3  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator+= (this=0x7fffffffd1f0, __s=0x0) at /usr/src/debug/gcc-9.1.1-1.fc30.x86_64/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_string.h:1178
No locals.
#4  0x000000000041a682 in process (scene=..., settings=..., json="", bin="") at tools/gltfpack.cpp:1439
        image = @0x46d100: {name = 0x46d1d0 "Image_3", uri = 0x0, buffer_view = 0x46d908, mime_type = 0x46d1b0 "image/png"}
        i = 0
        data = 0x4530a0
        qp = {pos_offset = {-1.14263856, -0.000703662634, -2.63861775}, pos_scale = 4.83839035, pos_bits = 14, uv_offset = {-2399.79492, -1098.69849}, uv_scale = {2475.4895, 1275.89636}, uv_bits = 12}
        json_images = "{\"uri\":\""
        json_textures = ""
        json_materials = ""
        json_buffer_views = ""
        json_accessors = ""
        json_meshes = ""
        json_nodes = ""
        json_skins = ""
        json_roots = ""
        json_animations = ""
        has_pbr_specular_glossiness = false
        view_offset = 0
        node_offset = 0
        mesh_offset = 0
        bytes_vertex = 0
        bytes_index = 0
        bytes_skin = 0
        bytes_time = 0
        bytes_keyframe = 0
        node_keep = std::vector<bool> of length -1125882108920646, capacity -1125898829637248 = {1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 
          0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0...}
        node_named = std::vector<bool> of length 34299809308, capacity 1125898727242048 = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
          0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
          0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...}
        node_remap = std::vector of length 35182226037202, capacity -2112495450 = {<error reading variable node_remap (Cannot access memory at address 0x1f7a87d68)>
#5  0x000000000041e643 in main (argc=6, argv=0x7fffffffdbe8) at tools/gltfpack.cpp:2143
        settings = {pos_bits = 14, uv_bits = 12, anim_freq = 30, compress = false, verbose = true}
        input = 0x7fffffffdfc0 "/home/arpu/Work/projects/vrland_assetssrc/models/bentley/bentley.glb"
        output = 0x7fffffffe008 "bent.glb"
```

**Comment by zeux** [comment]
Thanks! Your .gltf file has embedded image data and gltfpack currently assumes that all images come as external files.

**Comment by arpu** [comment]
ahh ok will export my glb as glb/gltf with external images 
i think this can be closed

**Comment by zeux** [comment]
Embedded images are supported properly as of 32399b04d5fa20c8b926640836014a78222ab6fe
